version: '2'
services:
  app:
    container_name: bot
    restart: always
    build: .
    volumes:
      - ./src:/bot/src
    ports:
      - '3000:3000'
    links:
      - database
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      YOUTUBE_TOKEN: ${YOUTUBE_TOKEN}
  database:
    container_name: database
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    logging:
      driver: 'none'
