name: Deploy
on:
  workflow_run:
    workflows: [Test]
    branches: [master]
    types:
      - completed

jobs:
  run-build:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Update release draft'
        id: 'tag'
        uses: release-drafter/release-drafter@v6
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        env:
          DOCKER_BUILDKIT: 1
          TAG: ${{ steps.tag.outputs.tag_name }}
        run: |
          docker build -t nicolajv/brotherbotv2:latest -t nicolajv/brotherbotv2:${{ env.TAG }} --build-arg VERSION=${{ env.TAG }} --target release .
      - name: Push image
        run: |
          docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
          docker push nicolajv/brotherbotv2 --all-tags
      - name: Update EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sudo docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
            sudo docker pull nicolajv/brotherbotv2
            docker-compose up -d --no-build
