name: Deploy
on:
  workflow_run:
    workflows: [Test]
    branches: [master]
    types:
      - completed

jobs:
  run-build:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Update release draft'
        id: 'tag'
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        env:
          DOCKER_BUILDKIT: 1
          TAG: ${{ steps.tag.outputs.tag_name }}
        run: |
          docker build -t nicolajv/brotherbotv2:latest -t nicolajv/brotherbotv2:${{ env.TAG }} --build-arg VERSION=${{ env.TAG }} --target release .
      - name: Push image
        run: |
          docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
          docker push -all-tags nicolajv/brotherbotv2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Terraform execute
        env:
          TAG: ${{ steps.tag.outputs.tag_name }}
        run: |
          cd terraform
          terraform init
          terraform apply -var="tag=${{ env.TAG }}" --auto-approve
