name: Deploy
on:
  workflow_run:
    workflows: [Test]
    branches: [master]
    types:
      - completed

jobs:
  run-build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t nicolajv/brotherbotv2 --build-arg VERSION=$(git rev-parse --short HEAD) --target release .
      - name: Push image
        run: |
          docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
          docker push nicolajv/brotherbotv2:latest
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Terraform execute
        run: |
          cd terraform
          terraform init
          terraform apply --auto-approve
