name: Build
on:
  push:
  workflow_dispatch:

jobs:
  run-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sign in to Docker
        if: github.ref == 'refs/heads/master'
        run: docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
      - name: Build
        run: docker-compose build --build-arg VERSION=$(git rev-parse --short HEAD)
      - name: Collect coverage
        if: github.ref == 'refs/heads/master'
        run: docker cp $(docker run -d nicolajv/brotherbotv2:latest tail -f /dev/null):/bot/coverage .
      - name: Push image
        if: github.ref == 'refs/heads/master'
        run: docker push nicolajv/brotherbotv2:latest
      - name: Publish code coverage
        if: github.ref == 'refs/heads/master'
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: '${{ secrets.CC_TEST_REPORTER_ID }}'
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage.lcov:lcov
  deploy:
    name: Deploy
    needs: run-build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AWS_KEY }}
          known_hosts: ${{ secrets.AWS_KNOWN_HOSTS }}
      - name: Testy
        run: ssh ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} && mkdir -p "BrotherBotV2" && cd "$_" && docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}' && docker pull nicolajv/brotherbotv2 && docker-compose up -d --no-build && docker logout