name: Build
on:
  push:
  workflow_dispatch:

jobs:
  run-build:
    name: Run build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sign in to Docker
        if: github.ref == 'refs/heads/master'
        run: docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
      - name: Build
        run: docker-compose build
      - name: Tag image
        if: github.ref == 'refs/heads/master'
        run: docker tag brotherbotv2_app nicolajv/brotherbotv2:latest
      - name: Push
        if: github.ref == 'refs/heads/master'
        run: docker push nicolajv/brotherbotv2:latest
  deploy:
    name: Deploy
    needs: run-build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          working-directory: /home/ubuntu/BrotherBotV2
          command: docker-compose pull; docker-compose up -d