name: Test
on:
  push:
    branches-ignore:
      - master

jobs:
  run-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build --build-arg VERSION=$(git rev-parse --short HEAD) --target production-build .
          docker build --build-arg VERSION=$(git rev-parse --short HEAD) --target test-export . --output coverage
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: '${{ secrets.CC_TEST_REPORTER_ID }}'
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/coverage.lcov:lcov
